export interface client {

    address: string,
    city: string,
    postalCode: string,
    country: string,
    activity: string,
    responsible: string,
    phone: string,
    fax: string,
    email: string,
    bank: string,
    rib: string,
    domiciliation: string,
    fiscalID: string,
    payment: string,
    daysCount: number,
    delay: number,
    type: string,
    accounting: string,
    nature: string,
    currency: string,
    agent: string,
    isVATSubject: boolean,
    isBlockedAccount: boolean,
    isFODECExemption: boolean,
    isVATExemption: boolean,
    isCICTExemption: boolean,
    isStampExemption: boolean,
    option1: boolean,
    option2 : boolean,
    option3 : boolean
    }